




[bar/topbar]
; monitor = ${env:MONITOR:HDMI-1}
; width = 100%
; height = 26
; offset-x = 1%
; offset-y = 1%
; radius = 3
; fixed-center = true

font-0 = Iosevka:pixelsize=10;1

background = ${colors.background}
foreground = ${colors.foreground}

; for underlines/overlines
; line-size = 2
; line-color = #fff

border-top-size = 3
border-bottom-size = 1
; border-left-size = 8
; border-right-size = 8
border-color = ${colors.background}

padding-left = 2
padding-right = 2

module-margin-left = 2
module-margin-right = 2



modules-left = i3 xwindow
; modules-center = memory cpu filesystem wlan eth temperature
modules-right = alsa user date powermenu

; tray-position = right
; tray-padding = 2
; tray-background = #0063ff

; wm-restack = i3

; override-redirect = true

; scroll-up = i3wm-wsnext
; scroll-down = i3wm-wsprev

; cursor-click = pointer
; cursor-scroll = ns-resize























[bar/bottombar]
font-0 = Iosevka:pixelsize=10;1
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}
padding-left = 2
padding-right = 2

border-top-size = 3
border-color = ${colors.background}

modules-left = memory cpu filesystem temperature
; modules-center = 
modules-right = network-traffic wlan eth

module-margin-left = 2
module-margin-right = 2