import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"
# size = 14
# offset.x = 1
offset.y = 0

